require('dotenv').config();

const appName = process.env.PM2_APP_NAME || 'omnizap-system';

const baseEnv = {
  NODE_ENV: 'production',
  COMMAND_PREFIX: '/',
  LOG_LEVEL: 'info',
  DB_LOG_EVERY_QUERY: 'false',
  DB_MONITOR_ENABLED: 'false',
  LID_BACKFILL_ON_START: 'false',
  STICKER_CLASSIFICATION_BACKGROUND_ENABLED: 'true',
  STICKER_CLASSIFICATION_BACKGROUND_CONCURRENCY: '2',
  STICKER_CLASSIFICATION_BACKGROUND_BATCH_SIZE: '8',
  STICKER_REPROCESS_QUEUE_ENABLED: 'true',
  STICKER_REPROCESS_MAX_PER_CYCLE: '8',
  STICKER_REPROCESS_MODEL_UPGRADE_SCAN_LIMIT: '120',
  STICKER_REPROCESS_LOW_CONFIDENCE_SCAN_LIMIT: '90',
  STICKER_REPROCESS_PRIORITY_BACKFILL_SCAN_LIMIT: '120',
  STICKER_AUTO_PACK_BY_TAGS_ENABLED: 'true',
  STICKER_AUTO_PACK_BY_TAGS_MAX_ADDITIONS_PER_CYCLE: '120',
  STICKER_AUTO_PACK_BY_TAGS_RETRO_CONSOLIDATION_MUTATION_LIMIT: '800',
  STICKER_WORKER_PIPELINE_ENABLED: 'true',
  STICKER_WORKER_PIPELINE_INLINE_POLLER_ENABLED: 'false',
  STICKER_WORKER_PIPELINE_SCHEDULER_INTERVAL_MS: '30000',
  STICKER_WORKER_PIPELINE_POLLER_INTERVAL_MS: '12000',
  STICKER_WORKER_CLASSIFICATION_CADENCE_MS: '180000',
  STICKER_WORKER_CURATION_CADENCE_MS: '300000',
  STICKER_WORKER_REBUILD_CADENCE_MS: '420000',
  STICKER_DEDICATED_WORKERS_ENABLED: 'true',
  STICKER_DEDICATED_WORKER_POLL_INTERVAL_MS: '10000',
  STICKER_DEDICATED_WORKER_IDLE_BACKOFF_MULTIPLIER: '1.8',
  STICKER_DEDICATED_WORKER_IDLE_MAX_POLL_INTERVAL_MS: '60000',
  STICKER_DEDICATED_WORKER_IDLE_JITTER_PERCENT: '15',
  STICKER_DOMAIN_EVENT_CONSUMER_POLLER_INTERVAL_MS: '5000',
  STICKER_SCORE_SNAPSHOT_REFRESH_INTERVAL_MS: '900000',
  STICKER_SCORE_SNAPSHOT_BATCH_SIZE: '60',
};

module.exports = {
  apps: [
    {
      name: `${appName}-production`,
      script: './index.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '3G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-out.log`,
      error_file: `logs/${appName}-error.log`,
      env: {
        ...baseEnv,
      },
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: `${appName}-worker-classification`,
      script: './scripts/sticker-worker-task.mjs',
      args: '--task-type classification_cycle',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-worker-classification-out.log`,
      error_file: `logs/${appName}-worker-classification-error.log`,
      env: {
        ...baseEnv,
      },
      kill_timeout: 5000,
    },
    {
      name: `${appName}-worker-curation`,
      script: './scripts/sticker-worker-task.mjs',
      args: '--task-type curation_cycle',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-worker-curation-out.log`,
      error_file: `logs/${appName}-worker-curation-error.log`,
      env: {
        ...baseEnv,
      },
      kill_timeout: 5000,
    },
    {
      name: `${appName}-worker-rebuild`,
      script: './scripts/sticker-worker-task.mjs',
      args: '--task-type rebuild_cycle',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-worker-rebuild-out.log`,
      error_file: `logs/${appName}-worker-rebuild-error.log`,
      env: {
        ...baseEnv,
      },
      kill_timeout: 5000,
    },
  ],
};
