require('dotenv').config();

const appName = process.env.PM2_APP_NAME || 'omnizap-system';

const baseEnv = {
  NODE_ENV: 'production',
  COMMAND_PREFIX: '/',
  LOG_LEVEL: 'info',
  DB_LOG_EVERY_QUERY: 'false',
  DB_MONITOR_ENABLED: 'false',
  LID_BACKFILL_ON_START: 'false',
  STICKER_CLASSIFICATION_BACKGROUND_ENABLED: 'true',
  STICKER_REPROCESS_QUEUE_ENABLED: 'true',
  STICKER_AUTO_PACK_BY_TAGS_ENABLED: 'true',
  STICKER_WORKER_PIPELINE_ENABLED: 'true',
  STICKER_WORKER_PIPELINE_INLINE_POLLER_ENABLED: 'true',
  STICKER_DEDICATED_WORKERS_ENABLED: 'true',
};

module.exports = {
  apps: [
    {
      name: `${appName}-production`,
      script: './index.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '3G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-out.log`,
      error_file: `logs/${appName}-error.log`,
      env: {
        ...baseEnv,
      },
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: `${appName}-worker-classification`,
      script: './scripts/sticker-worker-task.mjs',
      args: '--task-type classification_cycle',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-worker-classification-out.log`,
      error_file: `logs/${appName}-worker-classification-error.log`,
      env: {
        ...baseEnv,
      },
      kill_timeout: 5000,
    },
    {
      name: `${appName}-worker-curation`,
      script: './scripts/sticker-worker-task.mjs',
      args: '--task-type curation_cycle',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-worker-curation-out.log`,
      error_file: `logs/${appName}-worker-curation-error.log`,
      env: {
        ...baseEnv,
      },
      kill_timeout: 5000,
    },
    {
      name: `${appName}-worker-rebuild`,
      script: './scripts/sticker-worker-task.mjs',
      args: '--task-type rebuild_cycle',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: `logs/${appName}-worker-rebuild-out.log`,
      error_file: `logs/${appName}-worker-rebuild-error.log`,
      env: {
        ...baseEnv,
      },
      kill_timeout: 5000,
    },
  ],
};
