ALTER TABLE rpg_player_pokemon
  ADD COLUMN is_shiny TINYINT(1) NOT NULL DEFAULT 0 AFTER moves_json;

CREATE TABLE IF NOT EXISTS rpg_group_biome (
  group_jid VARCHAR(255) PRIMARY KEY,
  biome_key VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
