CREATE TABLE IF NOT EXISTS message_analysis_event (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  message_id VARCHAR(255) NULL,
  chat_id VARCHAR(255) NULL,
  sender_id VARCHAR(255) NULL,
  sender_name VARCHAR(120) NULL,
  upsert_type VARCHAR(32) NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'whatsapp',
  is_group TINYINT(1) NOT NULL DEFAULT 0,
  is_from_bot TINYINT(1) NOT NULL DEFAULT 0,
  is_command TINYINT(1) NOT NULL DEFAULT 0,
  command_name VARCHAR(64) NULL,
  command_args_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  command_known TINYINT(1) NULL,
  command_prefix VARCHAR(8) NULL,
  message_kind VARCHAR(48) NOT NULL DEFAULT 'other',
  has_media TINYINT(1) NOT NULL DEFAULT 0,
  media_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  text_length INT UNSIGNED NOT NULL DEFAULT 0,
  processing_result VARCHAR(64) NOT NULL DEFAULT 'processed',
  error_code VARCHAR(96) NULL,
  metadata JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_message_analysis_created (created_at),
  INDEX idx_message_analysis_chat_created (chat_id, created_at),
  INDEX idx_message_analysis_sender_created (sender_id, created_at),
  INDEX idx_message_analysis_command_created (command_name, created_at),
  INDEX idx_message_analysis_kind_created (message_kind, created_at),
  INDEX idx_message_analysis_result_created (processing_result, created_at),
  INDEX idx_message_analysis_is_command_created (is_command, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

